#!/bin/sh
set -e

if [ "$1" = remove ] && [ -d /run/systemd/system ]; then
    systemctl stop airsim-agent.service airsim-installerd.service || true
    systemctl disable airsim-agent.service airsim-installerd.service >/dev/null || true
fi

exit 0
